(()=>{
'use strict';
const canvas=document.getElementById('game');
const gl=canvas.getContext('webgl',{antialias:true,powerPreference:'high-performance'});
if(!gl){document.getElementById('status').textContent='WebGL is not supported on this device.';return;}
const ui={menu:document.getElementById('menu'),hud:document.getElementById('hud'),start:document.getElementById('start'),load:document.getElementById('load'),hp:document.getElementById('hp'),xp:document.getElementById('xp'),level:document.getElementById('level'),wrath:document.getElementById('wrath'),quest:document.getElementById('quest'),msg:document.getElementById('msg'),touch:document.getElementById('touch')};
const vs=`attribute vec3 aPos;attribute vec3 aNormal;uniform mat4 uMVP;uniform mat4 uModel;uniform vec3 uColor;uniform vec3 uLight;varying vec3 vColor;varying float vY;void main(){vec3 n=normalize(mat3(uModel)*aNormal);float l=max(.2,dot(n,normalize(uLight)));vColor=uColor*(.32+.68*l);vY=(uModel*vec4(aPos,1.)).y;gl_Position=uMVP*vec4(aPos,1.);}`;
const fs=`precision mediump float;varying vec3 vColor;varying float vY;uniform float uGlow;void main(){vec3 c=mix(vColor,vec3(1.,.78,.25),uGlow);gl_FragColor=vec4(c,1.);}`;
function sh(t,s){const x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);return x}
const p=gl.createProgram();gl.attachShader(p,sh(gl.VERTEX_SHADER,vs));gl.attachShader(p,sh(gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);gl.useProgram(p);
const A=gl.getAttribLocation(p,'aPos'),N=gl.getAttribLocation(p,'aNormal'),MVP=gl.getUniformLocation(p,'uMVP'),MODEL=gl.getUniformLocation(p,'uModel'),COLOR=gl.getUniformLocation(p,'uColor'),LIGHT=gl.getUniformLocation(p,'uLight'),GLOW=gl.getUniformLocation(p,'uGlow');gl.uniform3f(LIGHT,-.4,1,.25);
function mesh(v){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(v),gl.STATIC_DRAW);return{b,n:v.length/6}}
function cube(){const f=[];const faces=[[[0,0,-1],[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1]],[[0,0,1],[-1,-1,1],[-1,1,1],[1,1,1],[1,-1,1]],[[-1,0,0],[-1,-1,-1],[-1,1,-1],[-1,1,1],[-1,-1,1]],[[1,0,0],[1,-1,-1],[1,-1,1],[1,1,1],[1,1,-1]],[[0,1,0],[-1,1,-1], [1,1,-1],[1,1,1],[-1,1,1]],[[0,-1,0],[-1,-1,-1],[-1,-1,1],[1,-1,1],[1,-1,-1]]];for(const q of faces){const n=q[0],a=q[1],b=q[2],c=q[3],d=q[4];for(const t of [a,b,c,a,c,d])f.push(t[0],t[1],t[2],n[0],n[1],n[2]);}return mesh(f)}
const C=cube();
function mat(){return new Float32Array(16)}function identity(){const m=mat();m[0]=m[5]=m[10]=m[15]=1;return m}function mul(a,b){const o=mat();for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}function model(x,y,z,sx,sy,sz,ry=0){const m=identity(),c=Math.cos(ry),s=Math.sin(ry);m[0]=c*sx;m[2]=-s*sx;m[5]=sy;m[8]=s*sz;m[10]=c*sz;m[12]=x;m[13]=y;m[14]=z;return m}function perspective(f,a,n,far){const m=mat(),t=1/Math.tan(f/2);m[0]=t/a;m[5]=t;m[10]=(far+n)/(n-far);m[11]=-1;m[14]=2*far*n/(n-far);return m}function look(ex,ey,ez,cx,cy,cz){let z=[ex-cx,ey-cy,ez-cz],zl=Math.hypot(...z);z=z.map(v=>v/zl);let x=[z[2],0,-z[0]],xl=Math.hypot(...x);x=x.map(v=>v/xl);let y=[x[1]*z[2]-x[2]*z[1],x[2]*z[0]-x[0]*z[2],x[0]*z[1]-x[1]*z[0]];return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-(x[0]*ex+x[1]*ey+x[2]*ez),-(y[0]*ex+y[1]*ey+y[2]*ez),-(z[0]*ex+z[1]*ey+z[2]*ez),1])}
function draw(vp,m,c,g=0){gl.uniformMatrix4fv(MVP,false,mul(vp,m));gl.uniformMatrix4fv(MODEL,false,m);gl.uniform3fv(COLOR,c);gl.uniform1f(GLOW,g);gl.bindBuffer(gl.ARRAY_BUFFER,C.b);gl.enableVertexAttribArray(A);gl.vertexAttribPointer(A,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(N);gl.vertexAttribPointer(N,3,gl.FLOAT,false,24,12);gl.drawArrays(gl.TRIANGLES,0,C.n)}
const V={ground:[.32,.22,.12],stone:[.42,.29,.16],wall:[.58,.40,.22],roof:[.24,.14,.08],gold:[.75,.55,.18],skin:[.58,.32,.18],cloth:[.12,.09,.07],enemy:[.42,.11,.08],blue:[.08,.22,.32],water:[.05,.20,.27],green:[.16,.30,.12],white:[.75,.67,.48]};
const keys={},touch={};let active=false,last=0,yaw=0,attack=0,dodge=0,block=false,shake=0;
const S={x:0,z:34,hp:100,max:100,xp:0,level:1,wrath:0,kills:0};
const enemies=[{x:15,z:17,hp:45,max:45,t:0,kind:0},{x:-18,z:10,hp:45,max:45,t:.8,kind:0},{x:24,z:-8,hp:55,max:55,t:1.4,kind:1},{x:-25,z:-14,hp:55,max:55,t:2,kind:1},{x:7,z:-8,hp:140,max:140,t:1.1,boss:true,kind:2}];
const sparks=[];const buildings=[[-34,-32,10,6,8],[-17,-46,12,7,9],[18,-45,12,7,9],[36,-30,10,6,8],[-43,8,9,6,8],[43,8,9,6,8],[-39,31,11,7,9],[39,31,11,7,9]];
const palms=[[-50,-5],[-50,25],[50,-8],[51,25],[-60,-35],[60,-35]];const npcs=[{x:-8,z:17,c:V.white},{x:13,z:8,c:V.gold},{x:-14,z:-2,c:V.white}];
function resize(){const d=Math.min(devicePixelRatio||1,1.5),w=Math.floor(innerWidth*d),h=Math.floor(innerHeight*d);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}}
function say(t){ui.msg.textContent=t;ui.msg.classList.add('show');clearTimeout(say.t);say.t=setTimeout(()=>ui.msg.classList.remove('show'),1800)}
function uiUpdate(){ui.hp.textContent=Math.max(0,Math.ceil(S.hp));ui.xp.textContent=S.xp;ui.level.textContent=S.level;ui.wrath.textContent=Math.floor(S.wrath);document.getElementById('hpFill').style.width=(S.hp/S.max*100)+'%';document.getElementById('xpFill').style.width=(S.xp)+'%';document.getElementById('wrathFill').style.width=S.wrath+'%';ui.quest.textContent=S.kills<3?'Defeat the Uruk Guardians: '+S.kills+' / 3':'Reach the Great Gate of Uruk.'}
function start(load=false){active=true;ui.menu.classList.add('hidden');ui.hud.classList.remove('hidden');ui.touch.classList.toggle('hidden',!('ontouchstart'in window));if(load){try{Object.assign(S,JSON.parse(localStorage.getItem('gilgamesh3d')||'{}'));say('Chronicle loaded.')}catch(e){}}else say('WELCOME TO URUK');uiUpdate()}
function save(){localStorage.setItem('gilgamesh3d',JSON.stringify(S));say('Chronicle saved.')}
function hit(e,dmg){if(e.dead)return;e.hp-=dmg;for(let i=0;i<7;i++)sparks.push({x:e.x,z:e.z,y:1+Math.random()*1.4,vx:(Math.random()-.5)*5,vz:(Math.random()-.5)*5,life:.45});if(e.hp<=0){e.dead=true;S.kills++;S.xp+=e.boss?60:20;S.wrath=Math.min(100,S.wrath+(e.boss?35:15));if(S.xp>=100){S.xp-=100;S.level++;S.max+=12;S.hp=S.max;say('LEVEL UP · THE KING GROWS STRONGER')}else say(e.boss?'CAPTAIN DEFEATED':'GUARDIAN DEFEATED');uiUpdate()}}
function attackNow(){if(!active||attack>0)return;attack=.38;const fx=-Math.sin(yaw),fz=-Math.cos(yaw);for(const e of enemies){if(e.dead)continue;const dx=e.x-S.x,dz=e.z-S.z,d=Math.hypot(dx,dz),dot=(dx*fx+dz*fz)/(d||1);if(d<3.2&&dot>.25)hit(e,e.boss?24:34)}}
function wrathNow(){if(!active||S.wrath<100)return;S.wrath=0;attack=.8;shake=.35;for(const e of enemies)if(!e.dead&&Math.hypot(e.x-S.x,e.z-S.z)<7)hit(e,e.boss?70:80);say('ROYAL WRATH');uiUpdate()}
function move(dt){let f=(keys.w||keys.ArrowUp||touch.w?1:0)-(keys.s||keys.ArrowDown||touch.s?1:0),r=(keys.d||keys.ArrowRight||touch.d?1:0)-(keys.a||keys.ArrowLeft||touch.a?1:0);if(!f&&!r)return;const l=Math.hypot(f,r)||1;f/=l;r/=l;const speed=dodge>0?7:5.2;S.x+=(Math.cos(yaw)*r-Math.sin(yaw)*f)*speed*dt;S.z+=(Math.sin(yaw)*r+Math.cos(yaw)*f)*speed*dt;S.x=Math.max(-62,Math.min(62,S.x));S.z=Math.max(-62,Math.min(62,S.z))}
function update(dt){if(!active)return;move(dt);if(attack>0)attack-=dt;if(dodge>0)dodge-=dt;if(shake>0)shake-=dt;for(const e of enemies){if(e.dead)continue;e.t-=dt;const dx=S.x-e.x,dz=S.z-e.z,d=Math.hypot(dx,dz);if(d<15){e.x+=dx/d*(e.boss?1.1:.8)*dt;e.z+=dz/d*(e.boss?1.1:.8)*dt}if(d<2.2&&e.t<=0&&!dodge){e.t=e.boss?1.1:1.5;if(!block)S.hp-=e.boss?10:6;if(S.hp<=0){S.hp=S.max;S.x=0;S.z=34;say('THE KING RISES AGAIN')}}}for(let i=sparks.length-1;i>=0;i--){const s=sparks[i];s.x+=s.vx*dt;s.z+=s.vz*dt;s.y+=.8*dt;s.life-=dt;if(s.life<=0)sparks.splice(i,1)}if(S.kills>=3&&S.z<-48){S.kills=3;ui.quest.textContent='Chapter I complete · The western road awaits.';say('CHAPTER I COMPLETE');}uiUpdate()}
function palm(x,z,vp){draw(vp,model(x,2.4,z,1,4.8,1),V.wood||V.stone);draw(vp,model(x-.9,5,z,2.3,.35,.6,.5),V.green);draw(vp,model(x+.9,5,z,2.3,.35,.6,-.5),V.green);draw(vp,model(x,5,z-1,1.7,.35,.6,0),V.green)}
function character(x,z,rot,body,enemy=false,boss=false){draw(VP,model(x,.9,z,.72,1.8,.55,rot),body);draw(VP,model(x,2.25,z,.48,.5,.48,rot),enemy?V.enemy:V.skin);draw(VP,model(x-.35,.55,z,.22,.9,.22,rot),V.cloth);draw(VP,model(x+.35,.55,z,.22,.9,.22,rot),V.cloth);if(!enemy)draw(VP,model(x,-.0,z,.9,.12,.7,rot),V.gold);else if(boss)draw(VP,model(x,3.05,z,.75,.18,.75,rot),V.gold)}
let VP;
function render(){resize();gl.enable(gl.DEPTH_TEST);gl.clearColor(.035,.06,.09,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const w=canvas.width,h=canvas.height;const P=perspective(1.0,w/h,.1,180);const ex=S.x+Math.sin(yaw)*9+(Math.random()-.5)*shake*1.2,ez=S.z+Math.cos(yaw)*9+(Math.random()-.5)*shake*1.2;VP=mul(P,look(ex,6.2,ez,S.x,1.4,S.z));
 draw(VP,model(0,-.65,0,140,.8,140),V.ground);
 for(let i=-6;i<=6;i++)draw(VP,model(i*9,.02,0,.07,.03,120),[.40,.28,.15]);for(let i=-6;i<=6;i++)draw(VP,model(0,.025,i*9,120,.03,.07),[.40,.28,.15]);
 for(const b of buildings){draw(VP,model(b[0],b[3]/2,b[1],b[2],b[3],b[4]),V.wall);draw(VP,model(b[0],b[3]+.65,b[1],b[2]*1.08,.9,b[4]*1.08,.78),V.roof);draw(VP,model(b[0],b[3]*.42,b[1]-b[4]/2-.04,1.5,2.7,.15),V.roof)}
 // Great Gate and temple
 draw(VP,model(0,4,-58,18,8,3),V.wall);draw(VP,model(-7,7,-58,3,7,4),V.gold);draw(VP,model(7,7,-58,3,7,4),V.gold);draw(VP,model(0,3,-58,6,6,4),V.roof);
 for(let y=0;y<3;y++)draw(VP,model(0,2+y*2.2,-12,18-y*3,1.8,14-y*2),y===2?V.gold:V.stone);
 for(const q of palms)palm(q[0],q[1],VP);for(const n of npcs)character(n.x,n.z,0,n.c,false,false);character(S.x,S.z,yaw,V.cloth,false,false);
 for(const e of enemies)if(!e.dead){character(e.x,e.z,Math.atan2(S.x-e.x,S.z-e.z),e.kind===1?V.blue:V.enemy,true,!!e.boss);draw(VP,model(e.x,e.boss?3.55:2.9,e.z,1.2,.08,.12),[.5,.06,.04]);draw(VP,model(e.x,e.boss?3.55:2.9,e.z,Math.max(.01,e.hp/e.max*1.2),.09,.12),V.gold)}
 for(const s of sparks)draw(VP,model(s.x,s.y,s.z,.12,.12,.12),V.gold,Math.min(1,s.life*2));
}
function loop(t){const dt=Math.min(.033,(t-last||16)/1000);last=t;update(dt);render();requestAnimationFrame(loop)}
window.addEventListener('keydown',e=>{keys[e.key]=true;if(e.key===' ')attackNow();if(e.key.toLowerCase()==='r')wrathNow();if(e.key==='Shift')dodge=.45;if(e.key.toLowerCase()==='q')block=true;if(e.key.toLowerCase()==='f')save()});window.addEventListener('keyup',e=>{keys[e.key]=false;if(e.key.toLowerCase()==='q')block=false});
ui.start.onclick=()=>start(false);ui.load.onclick=()=>start(true);document.querySelectorAll('[data-k]').forEach(b=>{const k=b.dataset.k;b.addEventListener('pointerdown',e=>{e.preventDefault();touch[k]=true},{passive:false});['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();touch[k]=false},{passive:false}))});document.querySelectorAll('[data-a]').forEach(b=>{const a=b.dataset.a;b.addEventListener('pointerdown',e=>{e.preventDefault();if(a==='attack')attackNow();if(a==='wrath')wrathNow();if(a==='dodge')dodge=.45;if(a==='block')block=true},{passive:false});if(a==='block')b.addEventListener('pointerup',()=>block=false)});
let drag=false,lastX=0;canvas.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX});canvas.addEventListener('pointermove',e=>{if(drag){yaw+=(e.clientX-lastX)*.006;lastX=e.clientX}});window.addEventListener('pointerup',()=>drag=false);
ui.touch.classList.add('hidden');ui.hud.classList.add('hidden');document.getElementById('boot').classList.add('hidden');requestAnimationFrame(loop);
})();